myaap/urls.py
from django.contrib import admin
from django.urls import path
from . views import *

urlpatterns = [
    
     path('list/',StudentListView .as_view(), name='student_list'),
     path('add/',StudentaddView .as_view(), name='student_add'),
     path('info/<int:student_id>/', StudentDetailView.as_view(), name='student_details'),
     path('edit/<str:encoded_id>/',StudentUpdateView .as_view(),name='student_edit'),
     path('generate_pdf/<int:student_id>/', GeneratePDFView.as_view(), name='generate_pdf'),

]

project1/urls.py
from django.contrib import admin
from django.urls import path,include

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# swagger settings
schema_view = get_schema_view(
   openapi.Info(
      title="Infinity Fire solution APIs",
      default_version='v0.2.0',
      description="Welcome to the API Documentation",
   ),
   public=True,
   permission_classes=[permissions.AllowAny]
)

  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myaap.urls')),

    #swagger links for the api documentation
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

myaap/models.py
from django.db import models
from ckeditor.fields import RichTextField

# model for student
class Student(models.Model): 
    first_name = models.CharField(max_length=127)
    last_name = models.CharField(max_length=127) 
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=127)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name


STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
    ]

class project(models.Model):
    student_id = models.ForeignKey(Student,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description  = RichTextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    start_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
DEPART_CHOICES =  [
    ('engineering', 'Engineering'),
    ('mechincal', 'Mechincal'),
    ('electrical', 'Electrical'),
    ('arts', 'Arts'),
    ('commerce', 'Commerce'),

    ]

class AcedemicInfo(models.Model):
    student_id = models.ForeignKey(Student,on_delete=models.CASCADE)
    roll_no = models.CharField(max_length=50)
    course = models.CharField(max_length=255)
    department = models.CharField(max_length=20, choices=DEPART_CHOICES, default='engineering')
    batch = models.CharField(max_length = 255)
    enroll_rate = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.course
    

myaap/views.py
from django.conf import settings
import os
import pdfkit
import tempfile

from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template.loader import get_template
from django.contrib import messages
from django.urls import reverse

from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework import generics,status
from rest_framework.response import Response
from rest_framework import generics, status, filters
from django.views import View
from drf_yasg.utils import swagger_auto_schema

from . models import *
from . serializers import StudentSerializer

from project1.response import render_html_response
from .templatetags.hashid_filters import hashids




# Create your views here.

class StudentListView(generics.ListAPIView):
    """
    View to get the listing of all students.
    Supports both HTML and JSON response formats.
    """
    serializer_class = StudentSerializer
    renderer_classes = [TemplateHTMLRenderer,JSONRenderer]
    template_name = 'student_list.html'
    
    def get_queryset(self):
       queryset = Student.objects.all()
       return queryset
    

    def get(self, request, *args, **kwargs):
        """
        Handle both AJAX (JSON) and HTML requests.
        """
        queryset = self.get_queryset()
        if request.accepted_renderer.format == 'html':
            context = {'students': queryset}
            return render_html_response(context, self.template_name)
        else:
            serializer = self.serializer_class(queryset, many=True)
            return Response(
                status_code=status.HTTP_200_OK,
                message="Data retrieved",
                data=serializer.data
            )
    
    

class StudentaddView(generics.ListAPIView):
    """
    View to get the listing of all contacts.
    Supports both HTML and JSON response formats.
    """
    serializer_class = StudentSerializer
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    template_name = 'student_form.html'

    @swagger_auto_schema(operation_id='Get Student Form')
    def get(self, request, *args, **kwargs):
        queryset = Student.objects.all()

        if request.accepted_renderer.format == 'html':
            serializer = self.serializer_class()  # Create an instance of the serializer
            context = {'students': queryset, 'serializer': serializer}
            return render_html_response(context, self.template_name)
        else:
            # Return a JSON response if the format is not HTML
            serializer = self.serializer_class(queryset, many=True)
            return Response(serializer.data)
        
    @swagger_auto_schema(operation_id='Post Student Form')   
    def post(self, request, *args, **kwargs):
        """
        Handle POST request to add or update a contact.
        """
        message = "Congratulations! your contact has been added successfully."
        serializer = self.serializer_class(data=request.data)
        
        if serializer.is_valid():
            serializer.save()

            if request.accepted_renderer.format == 'html':
                messages.success(request, message)
                return redirect('student_list')

            else:
                # Return JSON response with success message and serialized data
                return Response(status_code=status.HTTP_201_CREATED,
                                    message=message,
                                    data=serializer.data
                                    )
        else:
            # Invalid serializer data
            if request.accepted_renderer.format == 'html':
                # Render the HTML template with invalid serializer data
                context = {'serializer':serializer}
                return render_html_response(context,self.template_name)
            else:   
                # Return JSON response with error message
                return Response(status_code=status.HTTP_400_BAD_REQUEST,
                                    message="We apologize for the inconvenience, but please review the below information.",
                                    data=(serializer.errors))
            
        
class StudentUpdateView(generics.UpdateAPIView):
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    template_name = 'student_form.html'
    serializer_class = StudentSerializer

    
    def get_student_instance(self, encoded_id):
        try:
            # Decode the encoded_id using Hashids
            id = hashids.decode(encoded_id)[0]
            # Fetch the student instance by the decoded ID
            instance = Student.objects.get(pk=id)
            return instance
        except (IndexError, Student.DoesNotExist):
            return None

    def get(self, request, encoded_id, *args, **kwargs):
        # Fetch the student instance
        instance = self.get_student_instance(encoded_id)

        if instance:
            # If the student instance exists, proceed with rendering the form
            serializer = self.serializer_class(instance=instance, context={'request': request})
            context = {'serializer': serializer, 'instance': instance}
            return render(request, self.template_name, context)
        else:
            # Handle the case where the student instance does not exist
            messages.error(request, "You are not authorized to perform this action")
            return redirect(reverse('student_list'))



    def post(self, request, encoded_id, *args, **kwargs):
        data = request.data

        # Fetch the student instance
        instance = self.get_student_instance(encoded_id)

        if instance:
            # Initialize the serializer with the instance and provided data
            serializer = self.serializer_class(instance=instance, data=data)

            if serializer.is_valid():
                # If the serializer data is valid, save the updated student instance
                serializer.save()
                message = "Your student has been updated successfully!"

                if request.accepted_renderer.format == 'html':
                    # For HTML requests, display a success message and redirect to student_list
                    messages.success(request, message)
                    return redirect('student_list')
                else:
                    # For API requests, return a success response with serialized data
                    return Response({'message': message, 'data': serializer.data}, status=status.HTTP_200_OK)
            else:
                if request.accepted_renderer.format == 'html':
                    # For HTML requests with invalid data, render the template with error messages
                    context = {'serializer': serializer, 'instance': instance}
                    return render(request, self.template_name, context)
                else:
                    # For API requests with invalid data, return an error response with serializer errors
                    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        else:
            error_message = "You are not authorized to perform this action"
            if request.accepted_renderer.format == 'html':
                # For HTML requests with no instance, display an error message and redirect to student_list
                messages.error(request, error_message)
                return redirect('student_list')
            else:
                # For API requests with no instance, return an error response with an error message
                return Response({'message': error_message}, status=status.HTTP_400_BAD_REQUEST)



class StudentDetailView(View):
    template_name = 'student_view.html'

    def get(self, request, student_id, *args, **kwargs):
        try:
            # Fetch the student based on the provided student_id
            student = Student.objects.get(pk=student_id)
            
            # Retrieve projects and academic info related to this student
            projects = project.objects.filter(student_id=student)
            academic_info = AcedemicInfo.objects.filter(student_id=student)

            # Create a context dictionary with data specific to this student
            context = {
                'student_data': student,
                'projects': projects,
                'academic_info': academic_info,
            }

            return render(request, self.template_name, context)
        except Student.DoesNotExist:
            # Handle the case where the student does not exist
            messages.error(request, "Student not found")
            return redirect(reverse('student_list'))
        

class GeneratePDFView(View):
    def get(self, request, student_id, *args, **kwargs):
        try:
            # Fetch the student based on the provided student_id
            student = Student.objects.get(pk=student_id)

            # Retrieve projects and academic info related to this student
            projects = project.objects.filter(student_id=student)
            academic_info = AcedemicInfo.objects.filter(student_id=student)

            # Create a context dictionary with data specific to this student
            context = {
                'student_data': student,
                'projects': projects,
                'academic_info': academic_info,
            }

            # Specify the path to the wkhtmltopdf executable
            config = pdfkit.configuration(wkhtmltopdf='/usr/bin/wkhtmltopdf')

            # Render the HTML template to a string
            template = get_template('student_view.html')
            html = template.render(context)

            # Define the options for PDF generation
            options = {
                'page-size': 'A4',
                'margin-top': '10mm',
                'margin-right': '10mm',
                'margin-bottom': '10mm',
                'margin-left': '10mm',
            }

myaap/templates/base.html
{% load rest_framework %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

          {% block style %}{% endblock style %}


</head>
<body>
<!-- Display messages -->
{% for message in messages %}
    <div class="alert alert-secondary" role="alert">
        {{ message }}
    </div>
{% endfor %}
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

{% block body %}


{% endblock body %}

</body>
</html>

myaap/templates/project_deleted_email.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="text-center border">
            <h1 class="display-4">Your Project Has Been Deleted</h1>
            <p class="lead">Dear {{ student_name }},</p>
            <p>We regret to inform you that your project "{{ project_name }}" has been deleted.</p>
            <hr class="my-4">
            <p>If you have any questions or concerns, please contact us.</p>
            <p>Thank you,</p>
            <p>Your Project Management Team</p>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

myaap/templates/student_form.html
{% extends 'base.html' %}
{% load rest_framework %}
{% block title %}Student Form{% endblock title %}
{% block body %}
    <div class="container my-3 py-3">
        <div class="row">
          <div class="col-lg-6">
            <!-- Card Basic Info -->
              <div class="card" id="basic-info">
                <div class="card-header mt-0">
                    <h6>Student Form</h6>
                  </div>
                  <div class="card-body pt-0">
                      <form role="form" method="POST" autocomplete="off">
                         <div class='row mt-2'>
                              {% csrf_token %}
                              {% render_form serializer%}
                          </div>
                          <button class="btn btn-success btn-md float-end mt-2 mb-0 mx-2" type="submit">Save</button>
                          <a class="btn btn-secondary btn-md float-end mt-2 mb-0 mx-2" href="{% url 'student_list' %}">Back</a>
                      
                        </form>
                  </div>
              </div>

{% endblock body %}

myaap/templates/student_list.html
{% extends 'base.html' %}
{% load hashid_filters %}
{% block title %}Student List{% endblock title %}
{% block body %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Student List</h1>
        <a class="btn btn-primary" href="{% url 'student_add' %}">Add Student</a>
    </div>

    <!-- Enclose the table in a card for a better UI -->
    <div class="card">
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{ student.first_name }}</td>
                        <td>{{ student.last_name }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.phone_number }}</td>
                        <td style="text-align:center;">
                            <a class="btn btn-secondary btn-sm mx-2"
                               href="{% url 'student_edit' student.id|hashid_encode %}" tooltip="Edit"><i class="fa fa-edit"></i></a>
                               <a class="btn btn-secondary btn-sm"
                               href="{% url 'student_details' student.id %}"><i class="fa fa-eye" tooltip="View"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock body %}

myaap/templates/student_view.html
{% extends 'base.html' %}
{% load rest_framework %}

{% block title %}Details{% endblock title %}
{% block body %}



<div class="container mt-4" style="border:1px solid rgba(0,0,0,0.4); box-shadow:4px 2px rgba(0,0,0,0.2);">

    <div class="row">
        <div class="col-md-10 justify-content-center align-items-center">
            <div class="section-container">
                <div class="section-heading">
                    <h2 class="mb-4">Student Data</h2>
                </div>
                    <div class="card mb-4">
                        <div class="card-body">
                            <p class="card-text"><strong>First Name:</strong>{{ student_data.first_name }}</h5>
                            <p class="card-text"><strong>Last Name:</strong>{{ student_data.last_name }}</p>
                            <p class="card-text"><strong>Email:</strong> {{ student_data.email }}</p>
                            <p class="card-text"><strong>Phone Number:</strong> {{student_data.phone_number }}</p>
                        </div>
                    </div>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Projects Section -->
        <div class="col-md-5 justify-content-center align-items-center">
            <div class="section-container">
                <div class="section-heading">
                    <h2 class="mb-4">Projects</h2>
                </div>
                {% for project in projects %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="mb-4">Project Information</h5>
                            <p class="card-text"><strong>Project Name: </strong>{{ project.name }}</p>
                            <p class="card-text"><strong>Student ID: </strong>{{ project.student_id}}</p>
                            <p class="card-text"><strong>Status: </strong> {{ project.status }}</p>
                            <p class="card-text"><strong>Start Date: </strong> {{ project.start_date }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Academic Information Section -->
        <div class="col-md-5 justify-content-center align-items-center">
            <div class="section-container">
                <div class="section-heading">
                    <h2 class="mb-4">Academic Information</h2>
                </div>
                {% for info in academic_info %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ info.roll_no }}</h5>
                            <p class="card-text"><strong>Course:</strong> {{ info.course }}</p>
                            <p class="card-text"><strong>Department:</strong> {{ info.get_department_display }}</p>
                            <p class="card-text"><strong>Batch:</strong> {{ info.batch }}</p>
                            <p class="card-text"><strong>Enroll Rate:</strong> {{ info.enroll_rate }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <a class="btn btn-primary" href="{% url 'generate_pdf' student_data.id %}" role="button">Download PDF</a>
            
                   
        </div>
</div>



{% endblock body %}